name = "locora-pages"
type = "javascript"

account_id = "83952a1be987e4a12647732861a60925"
workers_dev = true

# Service binding to your API Worker
[[bindings]]
type = "service"
name = "API"            
service = "locora-api"
