name = "locora-api"
main = "src/index.ts"
compatibility_date = "2025-10-06"

[vars]
ENVIRONMENT = "dev"

[[services]]
binding = "WaitlistRatelimiter"
service = "ratelimiter"
type = "Rate limiter"
namespace_id = "1"