name = "locora-api"
main = "src/index.ts"
compatibility_date = "2025-10-06"

[dev]
port = 6767
local_protocol = "http"

[vars]
ENVIRONMENT = "dev"

[[ratelimits]]
name = "WaitlistRatelimiter"
namespace_id = "1"
simple = {limit = 5, period = 60}