name: Electron Builder

permissions:
  contents: write

on:
  push:
    branches: 
      - main
      - development

jobs:
  build:
    strategy:
      matrix:
        include: 
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set VITE_ENVIRONMENT in .env
        shell: bash
        working-directory: apps/app/locora
        run: |
          touch .env
          sed -i.bak '/^VITE_ENVIRONMENT=/d' .env
          echo "VITE_ENVIRONMENT=${{ github.ref_name }}" >> .env
          cat .env

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        working-directory: apps/app/locora
        run: npm ci
        
      - name: Lint
        working-directory: apps/app/locora
        run: |
          npm run lint

      - name: Building the App
        working-directory: apps/app/locora
        run: npm run build

      - name: Electron Build
        working-directory: apps/app/locora
        run: |
          npx electron-builder --${{ matrix.platform }} --publish never

      - name: Upload artifacts
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: locora-${{ matrix.platform }}
          path: |
            apps/app/locora/dist/**/*.dmg
            apps/app/locora/dist/**/*.zip
            apps/app/locora/dist/**/*.exe
          retention-days: ${{ github.ref_name == 'main' && 90 || 1 }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' &&
      (github.ref_name == 'main' || github.ref_name == 'development')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}-${{ github.run_number }}
          name: "Build for ${{ github.ref_name }}"
          prerelease: true
          files: release_artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ github.token }}
