name: Electron Builder

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [mac, win, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: apps/app/locora
        run: npm ci
        
      - name: Lint & type check
        working-directory: apps/app/locora
        run: |
          npm run lint
          npm run type-check

      - name: Building the App
        working-directory: apps/app/locora
        run: npm run build

      - name: Electron Build
        run: |
          npx electron-builder --${{ matrix.platform }} --publish never

      - name: Posting to Github Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Build for ${{ github.ref_name }}"
          draft: false
          prerelease: true
          body: "Automated build for branch ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: apps/app/locora/dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
